project/urls.py
from django.conf import settings
from django.conf.urls.defaults import include
from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.views.generic.simple import redirect_to


admin.autodiscover()

PROGRAM_PATTERN_CORE = r'[a-z](?:[0-9a-z]|_[0-9a-z])*'
EVENT_PATTERN_CORE =r'(?:[0-9a-z]|_[0-9a-z])*' 
SCOPE_ARG_PATTERN = r'(?P<scope>%s/%s)' % (
    PROGRAM_PATTERN_CORE, EVENT_PATTERN_CORE) 

sitemaps = {}

# Admin
urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^robots\.txt$', include('robots.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^$', redirect_to, {'url': '/%s/' % (settings.CURRENT_SCOPE)}),
    url(r'^%s/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "home.html"}, name='home'),
)

# Talks, etc.
urlpatterns += patterns('project.scipycon.talk.views',
    url(r'^%s/talks/$' % (SCOPE_ARG_PATTERN),
        'list_talks', name='list_talks'),
    url(r'^%s/my-talks/$' % (SCOPE_ARG_PATTERN),
        'list_my_talks', name='list_my_talks'),
    url(r'^%s/talks/talk/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'talk', name='talk_detail'),
    url(r'^%s/submit-talk/$' % (SCOPE_ARG_PATTERN),
        'submit_talk', name='scipycon_submit_talk'),
    url(r'^%s/edit-talk/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'edit_talk', name='scipycon_edit_talk'),
    url(r'^%s/list-talks/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'list_talks', name='scipycon_list_talk'),
    url(r'^%s/download_slides/$' % (SCOPE_ARG_PATTERN),
        'download_slides', name='scipycon_download_slides'),
    url(r'^%s/download_videos/$' % (SCOPE_ARG_PATTERN),
        'download_videos', name='scipycon_download_videos'),

    )

# Registration
urlpatterns += patterns('project.scipycon.registration.views',
    url(r'^%s/registrations/$' % (SCOPE_ARG_PATTERN), 'registrations',
        name='scipycon_registrations'),
    url(r'^%s/submit-registration/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "registration/submit-registration.html"},
        name='scipycon_submit_registration'),
    url(r'^%s/edit-registration/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'edit_registration', name='scipycon_edit_registration'),
    url(r'^%s/regstats/$'% (SCOPE_ARG_PATTERN),
        'regstats', name="regstats"),
    url(r'^%s/regstats/download$'% (SCOPE_ARG_PATTERN),
        'regstats_download', name="regstats_download"),
    url(r'^%s/manage_payments/$'% (SCOPE_ARG_PATTERN),
        'manage_payments', name="scipycon_manage_payments"),
    )

# Authentication and Profile
urlpatterns += patterns('project.scipycon.user.views',
    url(r'^%s/login/$' % (SCOPE_ARG_PATTERN),
        'login', name='scipycon_login'),
    url(r'^%s/logout/$' % (SCOPE_ARG_PATTERN),
        'logout', name='scipycon_logout'),
    url(r'^%s/account/$' % (SCOPE_ARG_PATTERN),
        'account', name='scipycon_account'),
    url(r'^%s/password/$' % (SCOPE_ARG_PATTERN),
        'password', name='scipycon_password'), # change pwd
    url(r'^%s/username/$' % (SCOPE_ARG_PATTERN),
        'username', name='scipycon_username'), # change uname
    url(r'^%s/edit-profile/$' % (SCOPE_ARG_PATTERN),
        'edit_profile', name='scipycon_edit_profile'),
    url(r'^%s/get-usernames/$' % (SCOPE_ARG_PATTERN),
        'get_usernames', name='scipycon_get_usernames'),
    url(r'^%s/get-user-dump/$' % (SCOPE_ARG_PATTERN),
        'get_user_dump', name='scipycon_get_usernames'),
    url(r'^%s/badge/$' % (SCOPE_ARG_PATTERN),
        'badge', name='scipycon_badge'))
    

# Proceedings
urlpatterns += patterns('project.scipycon.proceedings.views',
    url(r'^%s/proceedings/submit/$' % (SCOPE_ARG_PATTERN), 'submit',
        name='scipycon_submit_proceedings'),
    url(r'^%s/proceedings/submit/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'submit', name='scipycon_submit_proceedings'),
    url(r'^%s/proceedings/show_paper/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'show_paper', name='scipycon_show_paper'),
    )

# About pages and all other static html pages
urlpatterns += patterns('',
    url(r'^%s/about/accommodation/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/accommodation.html"},
        name='scipycon_accommodation'),
    url(r'^%s/about/food/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/food.html"},
        name='scipycon_food'),
 url(r'^%s/downloads/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "downloads.html"},
        name='scipycon_downloads'),
    url(r'^%s/about/venue/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/venue.html"},
        name='scipycon_venue'),
    url(r'^%s/about/reachingcampus/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/reachingcampus.html"},
        name='scipycon_reachingcampus'),
    url(r'^%s/about/contact/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/contact.html"},
        name='scipycon_contact'),
    url(r'^%s/about/day_zero/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/day_zero.html"},
        name='scipycon_day_zero'),
    url(r'^%s/about/day_one/$' % (SCOPE_ARG_PATTERN),
    	direct_to_template, {"template": "about/day_one.html"},
        name='scipycon_day_one'),
    url(r'^%s/about/day_two/$' % (SCOPE_ARG_PATTERN),
    	direct_to_template, {"template": "about/day_two.html"},
        name='scipycon_day_two'),
    url(r'^%s/about/speakerinfo/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/speakerinfo.html"},
        name='scipycon_sinfo'),        
    url(r'^%s/about/city/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/city.html"},
        name='scipycon_city'),
    url(r'^%s/talks-cfp/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "talk/talks-cfp.html"},
        name='scipycon_talks_cfp'),
    url(r'^%s/talks-cfp/schedule/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "talk/schedule.html"},
        name='scipycon_schedule'),
    url(r'^%s/talks-cfp/tutorial/$' % (SCOPE_ARG_PATTERN),
         direct_to_template, {"template": "about/tutorial.html"},
        name='scipycon_tutorial'),
    url(r'^%s/talks-cfp/sprint/$' % (SCOPE_ARG_PATTERN),
         direct_to_template, {"template": "talk/sprint-schedule.html"},
         name='scipycon_sprint_schedule'),
    url(r'^%s/talks-cfp/speakers/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "talk/speakers.html"},
        name='scipycon_speakers'),
    url(r'^%s/publicity/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/publicity.html"},
        name='scipycon_publicity'),
    url(r'^%s/about/fees/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/fees.html"},
        name='scipycon_fees'),
    url(r'^%s/organizers/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/organizers.html"},
        name='scipycon_organizers'),
    url(r'^%s/talks-cfp/conference/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "talk/conf_schedule.html"},
        name='scipycon_conference'),
    url(r'^%s/tutorial/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/tutorial.html"},
        name='scipycon_tutorial'),
    url(r'^%s/sprints/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/sprints.html"},
        name='scipycon_sprints'),
    url(r'^%s/certificates/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/certificates.html"},
        name='scipycon_certificates'),
    url(r'^%s/about/dates/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/important_dates.html"},
        name='scipycon_imp_dates'),
    url(r'^%s/about/sponsors/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/sponsors.html"},
        name='scipycon_sponsors'),
    url(r'^%s/about/accepted/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/accepted_abstracts.html"},
        name='scipycon_accepted_abstracts'),
    )

# Password reset
urlpatterns += patterns('django.contrib.auth.views',
     url(r'^password-reset/$', 'password_reset', name='scipycon_password_reset'),
     url(r'^password-reset-done/$', 'password_reset_done'),
     url(r'^password-reset-confirm/(?P<uidb36>[-\w]*)/(?P<token>[-\w]*)$', 'password_reset_confirm'),
     url(r'^password-reset-complete/$', 'password_reset_complete'),
)

handler404 = 'project.scipycon.views.handler404'
handler500 = 'project.scipycon.views.handler404'

# Serve static files in DEBUG = True mode
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),
    )

project/scipycon/base/models.py
from django.db import models


class Event(models.Model):
    """Data model which holds the data related to the scope or the event.
    """

    # Different states the Event can be in
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    )

    # Scope of the program, used as a URL prefix
    scope = models.CharField(max_length=255)

    # Name of the program
    name = models.CharField(max_length=255)

    # Event specific i.e version of the event
    turn = models.CharField(max_length=255)

    # Status of the program
    status = models.CharField(max_length=255, choices=STATUS_CHOICES)

    def __unicode__(self):
        return '%s %s' % (self.name, self.turn)

    def get_full_name(self):
        return self.__unicode__()


class Timeline(models.Model):
    """Timeline of the program
    """

    # Event with which this timeline is associated
    event = models.OneToOneField(Event)

    # Start of registration for the program
    registration_start = models.DateTimeField(blank=True, null=True)

    # End of registration for the program
    registration_end = models.DateTimeField(blank=True, null=True)

    # Start of Call for Papers
    cfp_start = models.DateTimeField(blank=True, null=True)

    # End of Call for Papers
    cfp_end = models.DateTimeField(blank=True, null=True)

    # Accepted papers announced
    accepted_papers_announced = models.DateTimeField(blank=True, null=True)

    # Deadline to submit proceedings paper
    proceedings_paper_deadline = models.DateTimeField(blank=True, null=True)

    # Start of the actual program
    event_start = models.DateTimeField(blank=True, null=True)

    # End of the actual program
    event_end = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return '%s %s' % (self.event.name, self.event.turn)


class ScopedBase(models.Model):
    """Base model which is in turn inherited by other models
    which needs to be scoped.
    """

    # Scope of entity in which it is visible
    scope = models.ForeignKey(Event)

    class Meta:
        abstract = True


class Paid(models.Model):
    event_start = models.DateTimeField(blank=True, null=True)

project/scipycon/talk/models.py
from django.db import models
from django.contrib.auth.models import User

from tagging import register
from tagging.fields import TagField
from tagging.utils import parse_tag_input

from project.scipycon.base import models as base_models


DURATION_CHOICES = (
    ('10', 'Lightning Talk (10 mins)'),
    ('20', 'Short Talk (20 mins)'),
    ('30', 'Standard Talk (30 mins)'),
    )

AUDIENCE_CHOICES = (
    ('nonprogrammers', 'Non Programmer'),
    ('beginers', 'Beginner Programmer'),
    ('intermediate', 'Intermediate Programmer'),
    ('advanced', 'Advanced Programmer'),
    )


class Talk(base_models.ScopedBase):
    """Defines talks at SciPy.in
    """

    slug = models.SlugField()

    speaker = models.ForeignKey(User)

    authors_bio = models.TextField()

    contact = models.EmailField()

    title = models.CharField(max_length=1024)

    abstract = models.TextField()

    topic = models.CharField(max_length=255, blank=True)

    duration = models.CharField(max_length=3, choices=DURATION_CHOICES)

    audience = models.CharField(max_length=32, choices=AUDIENCE_CHOICES, blank=True)

    approved = models.BooleanField(default=False)

    submitted = models.DateTimeField(auto_now_add=True)

    last_mod = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_tag_list(self):
        return parse_tag_input(self.tags)

project/templates/_errors.html
{% if messages %}<div id="messages">{% for message in messages %}{{ message }}{% endfor %}</div>{% endif %}
{% if form.errors %}<div id="errors">Please correct the errors below</div>{% endif %}

project/templates/_menu.html
<div id="left-inner">
  <ul>
    <li><a href="/{{ params.scope }}/">Home</a></li>
    <!--li>
      <a href="/{{ params.scope }}/download_slides/">
        <font color="red">Download Slides</font>
      </a>
    </li>
    <!--li>
      <a href="/{{ params.scope }}/download_videos/">
        Download Videos <font color="red">(New)</font>
      </a>
    </li> -->
    <!--li>
        <a href="/{{ params.scope }}/downloads/"><font color="red">Slides: Talks & Tutorials</a></font>
    </li-->
    <li><a href="/{{ params.scope }}/submit-registration/">Registration</a></li>
    <li>
      <ul>
        <li>
          <a href="/{{ params.scope }}/about/fees/">Fees </a>
        </li>
      </ul>
    </li>
    <li>
      Conference & CFP
      <ul>
        <li>
          <a href="/{{ params.scope }}/talks-cfp/">Call for Papers</a>
        </li>
        <li>
          <a href="/{{ params.scope }}/about/dates/">Important Dates</a>
        </li>
        <li>
          <a href="/{{ params.scope }}/talks-cfp/schedule/">Schedule</a>
		</li>
        <!--a href="/{{ params.scope }}/talks-cfp/conference/">
            Conference
          </a-->
        <!--li>
              <a href="/{{ params.scope }}/talks-cfp/tutorial/">
            Tutorial Schedule
              </a>
        </li>
        <li>
          <a href="/{{ params.scope }}/talks-cfp/sprint/">
            Sprint Plan &amp; Schedule
          </a>
        </li-->
        <li>
          <a href="/{{ params.scope }}/talks-cfp/speakers/">Invited Speakers</a>
        </li>
        <li><a href="/{{ params.scope }}/about/accepted">Accepted Abstracts</a></li>
        <!--{% if user.is_authenticated and user.talk_set.all %}
        <li><a href="/{{ params.scope }}/my-talks">My talks</a></li>
        <!--{% endif %}-->
	
      </ul>
    </li>
    <!-- <li>
      <a href="/{{ params.scope }}/tutorial/">
      Tutorials
      </a>
    </li>
    <li>
      <a href="/{{ params.scope }}/sprints/">
      Sprints
      </a>
    </li> -->
    <!--li>
      <a href="/{{ params.scope }}/certificates/">
      Certificates
      </a>
    </li-->
    <li>
      About
      <ul>
        <!-- <li>
          <a href="/{{ params.scope }}/about/accommodation/">
          Accommodation
          </a>
        </li>
        <li>
          <a href="/{{ params.scope }}/about/food/">Food</a>
        </li> -->
        <li><a href="/{{ params.scope }}/about/venue/">The Venue</a></li>
        <!-- <li><a href="/{{ params.scope }}/about/city/">Host City - Mumbai</a></li> -->
        <li>
          <a href="/{{ params.scope }}/about/reachingcampus/">Reaching the venue</a>
        </li>
	    <li>
          <a href="/{{ params.scope }}/about/contact/">Contact us</a>
        </li>
      </ul>
    </li>
    <!-- <li><a href="/{{ params.scope }}/publicity/">Publicity</a></li>
    <li><a href="/{{ params.scope }}/organizers/">Organizers</a></li> -->
    <li><a href="/{{ params.scope }}/about/sponsors/">Sponsors</a></li>
    <!--{% if user.is_staff %}
    <li><a href="/{{ params.scope }}/regstats/">Registration Statistics</a></li>
    {% endif %}
    {% if user.is_superuser %}
    <li><a href="/{{ params.scope }}/manage_payments/">Manage Payments</a></li>
    {% endif %}-->
    <!--li>SciPy.in 2011 Blog
		<ul>
			<li><a href="/{{ params.scope }}/about/day_zero/">Day 0</a></li>
			<li><a href="/{{ params.scope }}/about/day_one/">Day 1</a></li>
			<li><a href="/{{ params.scope }}/about/day_two/">Day 2</a></li>
		</ul>
	</li-->
	
	<!--li><a href="/{{ params.scope }}/about/speakerinfo/">Speaker Info</a></li-->
	
  </ul>
</div>

project/templates/_menu_user.html
<div id="menu-user">
    {% if user.is_authenticated %}
        {% if user.get_full_name %}
        <strong>{{ user.get_full_name }} &lt;{{ user.username }}&gt;</strong>
        {% else %}
            <strong>{{ user.username }}</strong>
        {% endif %} |

        <a href="/{{params.scope }}/account/">My profile</a> |

        {% if user.is_superuser %}
                <a href="/admin/">Administer</a> |
        {% endif %}

        <a href="/{{params.scope }}/logout/">Logout</a>
    {% else %}
        <a href="/{{params.scope }}/login/">Login</a>
    {% endif %}
</div>

project/templates/_right_menu.html
<div style=" border: 2px black solid; background-color:#C6E2FF;">
<center><h2 style="padding-left:2px;"><font color="#003F87"><b>News and Updates</b></h2></center>
<ul>
<li><a href="/{{ params.scope }}/downloads/"><font color="red"><b><u>Slides - Talks & Tutorials</b></u></a></font></li>
<li><a target="_blank" href="https://picasaweb.google.com/108547534465492743329/SciPyIn201227th29thDec"><font color="red"><u><b>Image Gallery</font></a></u></b>
<li><a target="_blank" href="http://urtalk.kpoint.com/playlist/view/152"><font color="red"><u><b>Video Recordings</font></a></u></b>
</ul>
</div>
<br>

<div id="right-inner">
  <h2><strong>Organizers</strong></h2>
  <p><ul>
    <li><a href="/scipyin/2011/about/sponsors/">
    <img src="/static/img/fossee.jpg" alt="FOSSEE Logo" title="FOSSEE Logo"
    width="220" /></a></li>
  </ul></p>
  <h2><strong>Sponsors</strong></h2>
  <p><ul>
  	<li><a href="/scipyin/2011/about/sponsors/">
    <img src="/static/img/mhrd_logo.png" alt="MHRD Logo"
    title="MHRD Logo" width=220/><br/></a></li>
    <li><a href="/scipyin/2011/about/sponsors/">
    <img src="/static/img/enthought_logo.png" alt="Enthought Logo"
    title="Enthought Logo"  width="220"/><br/></a></li>
  </ul></p>
  <h2><strong>Venue</strong></h2>
  <p><ul>
    <li><a href="/scipyin/2011/about/sponsors/">
    <img src="/static/img/iitb_logo.jpg" height=160 alt="IIT-B Logo"
    title="IIT-B Logo"  /><br/></a></li>
  </ul></p>
</div>

project/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us" xml:lang="en-us" >
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <title>{% block title %}{% endblock %} SciPy.in 2012, December 27 - 29, 2012, IIT Bombay, India</title>

  <link rel="stylesheet" type="text/css" href="/static/css/jquery.jgrowl.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/header.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/jquery-ui-lightness/jquery-ui-1.7.3.custom.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/styles-20100720.css" />

  <script type="text/javascript" src="/static/jquery/jquery.min.js"></script>
  <script type="text/javascript" src="/static/jquery/jquery-ui-1.7.3.custom.min.js"></script>
  <script type="text/javascript" src="/static/jquery/jquery.jgrowl_minimized.js"></script>
  <script type="text/javascript" src="/static/jquery/jquery.cookie.pack.js"></script>
  <script type="text/javascript" src="/static/js/kiwipycon.js"></script>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26098261-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

  {% block addscripts %}{% endblock %}

  <link rel="icon" href="/static/img/favicon.ico" type="image/x-icon" />

  <!--<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="/feeds/blog" />-->

</head>
<body>

<div id="logo" class="jumbotron subhead">
<div id="social-badge">
    	<a href="http://twitter.com/scipydotin" target="_blank"><img src="/static/img/twitter.png" alt="Twitter" Title="Connect to us of Twitter" style="border-style:solid; border-width:1px; border-color:white; border-radius:5px;" /></a>
    	<a href="https://www.facebook.com/scipydotin" target="_blank"><img src="/static/img/facebook.png" alt="Facebook" Title="Connect to us of Facebook" style="border-style:solid; border-width:1px; border-color:white; border-radius:5px;" /></a>
    </div>
    <div id="header">
        
  <center><table>
  <a href="/"><tr><td rowspan=2><img src="/static/img/scipyshiny_small.png" alt="SciPy.in Logo" title="SciPy.in Logo" width="190" height="180" /></a>
  {% block header %}
    <td><br><font size="8">SciPy.in 2012</font>
    <tr><td><font size="5">December 27 - 29, IIT Bombay, India</font>
    </table></center>
  {% endblock %}
    
    
  <!--{% include '_menu_user.html' %}-->
</div>
    
</div>


<div id="wrapper">
  <div id="left">
  {% include '_menu.html' %}
  </div>
  <div id="content">
  {% if user.is_authenticated %}
      {% include 'user/_usermenu.html' %}
  {% endif %}

    {% block content %}{% endblock %}
  </div>
  <div id="right">
  {% include '_right_menu.html' %}
  </div>
</div>

<div id="footer">
   <p rel="credits">Content by the <a href="/about/team/" alt="SciPy.in Team">SciPy.in Team</a>,
   website by <a href="http://hg.fossee.in/scipycon/file/tip/AUTHORS" alt="Website's Creators">FOSSEE using Kiwi Djangonauts original code</a>,
   hosting by <a href="http://fossee.in/" alt="Free and Open Source software in Science and Engineering Education">Free and Open Source software in Science and Engineering Education</a>,
   Rants, Bugs and Flames to: <a href="mailto:admin@scipy.in">admin@scipy.in</a>
   </p>
</div>

</body>
</html>