project/urls.py
from django.conf import settings
from django.conf.urls.defaults import include
from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.views.generic.simple import redirect_to


admin.autodiscover()

PROGRAM_PATTERN_CORE = r'[a-z](?:[0-9a-z]|_[0-9a-z])*'
EVENT_PATTERN_CORE =r'(?:[0-9a-z]|_[0-9a-z])*' 
SCOPE_ARG_PATTERN = r'(?P<scope>%s/%s)' % (
    PROGRAM_PATTERN_CORE, EVENT_PATTERN_CORE) 

sitemaps = {}

# Admin
urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^robots\.txt$', include('robots.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^$', redirect_to, {'url': '/%s/' % (settings.CURRENT_SCOPE)}),
    url(r'^%s/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "home.html"}, name='home'),
)

# Talks, etc.
urlpatterns += patterns('project.scipycon.talk.views',
    url(r'^%s/talks/$' % (SCOPE_ARG_PATTERN),
        'list_talks', name='list_talks'),
    url(r'^%s/my-talks/$' % (SCOPE_ARG_PATTERN),
        'list_my_talks', name='list_my_talks'),
    url(r'^%s/talks/talk/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'talk', name='talk_detail'),
    url(r'^%s/submit-talk/$' % (SCOPE_ARG_PATTERN),
        'submit_talk', name='scipycon_submit_talk'),
    url(r'^%s/edit-talk/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'edit_talk', name='scipycon_edit_talk'),
    url(r'^%s/list-talks/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'list_talks', name='scipycon_list_talk'),
    url(r'^%s/download_slides/$' % (SCOPE_ARG_PATTERN),
        'download_slides', name='scipycon_download_slides'),
    url(r'^%s/download_videos/$' % (SCOPE_ARG_PATTERN),
        'download_videos', name='scipycon_download_videos'),

    )

# Registration
urlpatterns += patterns('project.scipycon.registration.views',
    url(r'^%s/registrations/$' % (SCOPE_ARG_PATTERN), 'registrations',
        name='scipycon_registrations'),
    url(r'^%s/submit-registration/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "registration/submit-registration.html"},
        name='scipycon_submit_registration'),
    url(r'^%s/edit-registration/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'edit_registration', name='scipycon_edit_registration'),
    url(r'^%s/regstats/$'% (SCOPE_ARG_PATTERN),
        'regstats', name="regstats"),
    url(r'^%s/regstats/download$'% (SCOPE_ARG_PATTERN),
        'regstats_download', name="regstats_download"),
    url(r'^%s/manage_payments/$'% (SCOPE_ARG_PATTERN),
        'manage_payments', name="scipycon_manage_payments"),
    )

# Authentication and Profile
urlpatterns += patterns('project.scipycon.user.views',
    url(r'^%s/login/$' % (SCOPE_ARG_PATTERN),
        'login', name='scipycon_login'),
    url(r'^%s/logout/$' % (SCOPE_ARG_PATTERN),
        'logout', name='scipycon_logout'),
    url(r'^%s/account/$' % (SCOPE_ARG_PATTERN),
        'account', name='scipycon_account'),
    url(r'^%s/password/$' % (SCOPE_ARG_PATTERN),
        'password', name='scipycon_password'), # change pwd
    url(r'^%s/username/$' % (SCOPE_ARG_PATTERN),
        'username', name='scipycon_username'), # change uname
    url(r'^%s/edit-profile/$' % (SCOPE_ARG_PATTERN),
        'edit_profile', name='scipycon_edit_profile'),
    url(r'^%s/get-usernames/$' % (SCOPE_ARG_PATTERN),
        'get_usernames', name='scipycon_get_usernames'),
    url(r'^%s/get-user-dump/$' % (SCOPE_ARG_PATTERN),
        'get_user_dump', name='scipycon_get_usernames'),
    url(r'^%s/badge/$' % (SCOPE_ARG_PATTERN),
        'badge', name='scipycon_badge'))
    

# Proceedings
urlpatterns += patterns('project.scipycon.proceedings.views',
    url(r'^%s/proceedings/submit/$' % (SCOPE_ARG_PATTERN), 'submit',
        name='scipycon_submit_proceedings'),
    url(r'^%s/proceedings/submit/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'submit', name='scipycon_submit_proceedings'),
    url(r'^%s/proceedings/show_paper/(?P<id>\d+)/$' % (SCOPE_ARG_PATTERN),
        'show_paper', name='scipycon_show_paper'),
    )

# About pages and all other static html pages
urlpatterns += patterns('',
    url(r'^%s/about/accommodation/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/accommodation.html"},
        name='scipycon_accommodation'),
    url(r'^%s/about/food/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/food.html"},
        name='scipycon_food'),
 url(r'^%s/downloads/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "downloads.html"},
        name='scipycon_downloads'),
    url(r'^%s/about/venue/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/venue.html"},
        name='scipycon_venue'),
    url(r'^%s/about/reachingcampus/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/reachingcampus.html"},
        name='scipycon_reachingcampus'),
    url(r'^%s/about/contact/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/contact.html"},
        name='scipycon_contact'),
    url(r'^%s/about/day_zero/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/day_zero.html"},
        name='scipycon_day_zero'),
    url(r'^%s/about/day_one/$' % (SCOPE_ARG_PATTERN),
    	direct_to_template, {"template": "about/day_one.html"},
        name='scipycon_day_one'),
    url(r'^%s/about/day_two/$' % (SCOPE_ARG_PATTERN),
    	direct_to_template, {"template": "about/day_two.html"},
        name='scipycon_day_two'),
    url(r'^%s/about/speakerinfo/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/speakerinfo.html"},
        name='scipycon_sinfo'),        
    url(r'^%s/about/city/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/city.html"},
        name='scipycon_city'),
    url(r'^%s/talks-cfp/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "talk/talks-cfp.html"},
        name='scipycon_talks_cfp'),
    url(r'^%s/talks-cfp/schedule/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "talk/schedule.html"},
        name='scipycon_schedule'),
    url(r'^%s/talks-cfp/tutorial/$' % (SCOPE_ARG_PATTERN),
         direct_to_template, {"template": "about/tutorial.html"},
        name='scipycon_tutorial'),
    url(r'^%s/talks-cfp/sprint/$' % (SCOPE_ARG_PATTERN),
         direct_to_template, {"template": "talk/sprint-schedule.html"},
         name='scipycon_sprint_schedule'),
    url(r'^%s/talks-cfp/speakers/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "talk/speakers.html"},
        name='scipycon_speakers'),
    url(r'^%s/publicity/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/publicity.html"},
        name='scipycon_publicity'),
    url(r'^%s/about/fees/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/fees.html"},
        name='scipycon_fees'),
    url(r'^%s/organizers/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/organizers.html"},
        name='scipycon_organizers'),
    url(r'^%s/talks-cfp/conference/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "talk/conf_schedule.html"},
        name='scipycon_conference'),
    url(r'^%s/tutorial/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/tutorial.html"},
        name='scipycon_tutorial'),
    url(r'^%s/sprints/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/sprints.html"},
        name='scipycon_sprints'),
    url(r'^%s/certificates/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/certificates.html"},
        name='scipycon_certificates'),
    url(r'^%s/about/dates/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/important_dates.html"},
        name='scipycon_imp_dates'),
    url(r'^%s/about/sponsors/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/sponsors.html"},
        name='scipycon_sponsors'),
    url(r'^%s/about/accepted/$' % (SCOPE_ARG_PATTERN),
        direct_to_template, {"template": "about/accepted_abstracts.html"},
        name='scipycon_accepted_abstracts'),
    )

# Password reset
urlpatterns += patterns('django.contrib.auth.views',
     url(r'^password-reset/$', 'password_reset', name='scipycon_password_reset'),
     url(r'^password-reset-done/$', 'password_reset_done'),
     url(r'^password-reset-confirm/(?P<uidb36>[-\w]*)/(?P<token>[-\w]*)$', 'password_reset_confirm'),
     url(r'^password-reset-complete/$', 'password_reset_complete'),
)

handler404 = 'project.scipycon.views.handler404'
handler500 = 'project.scipycon.views.handler404'

# Serve static files in DEBUG = True mode
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),
    )

project/scipycon/talk/models.py
from django.db import models
from django.contrib.auth.models import User

from tagging import register
from tagging.fields import TagField
from tagging.utils import parse_tag_input

from project.scipycon.base import models as base_models


DURATION_CHOICES = (
    ('10', 'Lightning Talk (10 mins)'),
    ('20', 'Short Talk (20 mins)'),
    ('30', 'Standard Talk (30 mins)'),
    )

AUDIENCE_CHOICES = (
    ('nonprogrammers', 'Non Programmer'),
    ('beginers', 'Beginner Programmer'),
    ('intermediate', 'Intermediate Programmer'),
    ('advanced', 'Advanced Programmer'),
    )


class Talk(base_models.ScopedBase):
    """Defines talks at SciPy.in
    """

    slug = models.SlugField()

    speaker = models.ForeignKey(User)

    authors_bio = models.TextField()

    contact = models.EmailField()

    title = models.CharField(max_length=1024)

    abstract = models.TextField()

    topic = models.CharField(max_length=255, blank=True)

    duration = models.CharField(max_length=3, choices=DURATION_CHOICES)

    audience = models.CharField(max_length=32, choices=AUDIENCE_CHOICES, blank=True)

    approved = models.BooleanField(default=False)

    submitted = models.DateTimeField(auto_now_add=True)

    last_mod = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_tag_list(self):
        return parse_tag_input(self.tags)

project/scipycon/talk/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

#django
from django import forms

#django.contrib
from django.contrib.auth.models import User

#tagging
from tagging.forms import TagField

#scipycon
#from .models import TOPIC_CHOICES
from .models import DURATION_CHOICES
from .models import AUDIENCE_CHOICES


class TalkSubmitForm(forms.Form):
    """Submit talk form
    """
    authors_bio = forms.CharField(widget=forms.Textarea, required=True,
        label=u'Author(s) and short bio',
        help_text=u'(include a bit about your qualifications regarding your presentation topic)')
    contact = forms.EmailField(required=True, label=u'E-Mail ID',
        help_text=u'Provide your email ID',
        max_length=1024,
        widget=forms.TextInput(attrs={'size':'50'}))
    title = forms.CharField(required=True, label=u'Talk title',
        help_text=u'Title of proposed presentation',
        max_length=1024,
        widget=forms.TextInput(attrs={'size':'50'}))
    abstract = forms.CharField(widget=forms.Textarea, required=True,
        help_text=u'Summary of proposed presentation (In 300-700 words)')
#    outline = forms.CharField(widget=forms.Textarea, required=True,
#        help_text=u'Outline of proposed presentation (around 200 words)')
#    topic = forms.ChoiceField(choices=TOPIC_CHOICES,
#        label=u'Topic', help_text=u'Select one of the available options or enter other topic')
#    topic_other = forms.CharField(label=u'Other topic',
#        help_text=u'Description of your topic',
#        max_length=255,
#        required=False,
#        widget=forms.TextInput(attrs={'size':'50'}))
    topic = forms.CharField(label=u'Topic',
        help_text=u'Description of your topic or comma separated tags',
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'size':'50'}))
    duration = forms.ChoiceField(choices=DURATION_CHOICES, required=True,
        label=u'Preferred time slot', help_text=u'Select preferred time slot')
    audience = forms.ChoiceField(choices=AUDIENCE_CHOICES, label=u'Intended audience',
        help_text=u'Select one of the available options or enter other type of intended audience')
#    audience_other = forms.CharField(label=u'Other intended audience',
#        help_text=u'Description of intended audience (ie. Discordians)',
#        max_length=128,
#        required=False,
#        widget=forms.TextInput(attrs={'size':'50'}))
#    tags = TagField(max_length=255,
#        widget=forms.TextInput(attrs={'size':'50'}))

class TalkEditForm(TalkSubmitForm):
    id = forms.CharField(widget=forms.HiddenInput)

project/templates/talk/download-slides.html
{% extends "base.html" %}
{% block title %}Download Slides{% endblock %}

{% block content %}
<style>
th
{
    font-size:18px;
}
.tdstyle
{
    width:600px;
    height:40px;    
    text-align:center;
    vertical-align:middle;
    font-weight:bold;
}
a
{
    text-decoration:underline;
    color:#003F87;
}
</style>

<h1 class="title" id="top"><strong>Slides for Download</strong></h1>

<h3>This is an incomplete list, more slides will be uploaded soon. </h3><br>

<center><h2><u><b>TUTORIALS</b></u></h2></center>
<table name=main>
<tr bgcolor="C6E2FF">
    <th class=tdstyle style="width:210px;">Speaker
    <th class=tdstyle>Slides
    <tr>
    <td class=tdstyle style="width:210px;">Puneeth Chaganti, Prashant <td class=tdstyle><a target="_blank" href="http://scipy-lectures.github.com">Basic Python, IPython, numpy, scipy, matplotlib</a>
    <tr>
    <td class=tdstyle style="width:210px;">Prabhu Ramachandran <td class=tdstyle><a href="/static/files/slides/mayavi_tutorial.pdf">Basic 3D viz with Mayavi</a>
    <!--tr>
    <td class=tdstyle style="width:200px;">Ole Nielsen <td class=tdstyle>Geoprocessing with Python
    <tr>
    <td class=tdstyle style="width:200px;">Ole Nielsen	<td class=tdstyle>Geoprocessing with Python-->
    <!--tr>
    <td class=tdstyle style="width:200px;">Ajith Kumar <td class=tdstyle>Python for experiments in Physics-->
    <tr>
    <td class=tdstyle style="width:210px;">Prabhu Ramachandran/Puneeth<td class=tdstyle><a href="/static/files/slides/cython_tutorial.pdf">ETS Intro/Cython</a>
    <tr>
    <td class=tdstyle style="width:210px;">Ajith Kumar<td class=tdstyle><a href="/static/files/slides/expeyes.pdf">expEYES</a>
</tr>
</table>

<center><h2><u><b>TALKS</b></u></h2></center>
<table name=main>
<tr bgcolor="C6E2FF">
    <th class=tdstyle style="width:210px;">Speaker
    <th class=tdstyle>Slides
    <!--tr>
    <td class=tdstyle>14:00 - 14:15 <td class=tdstyle>Prabhu Ramachandran	<td class=tdstyle>Inauguration
    <tr>
    <td class=tdstyle>14:15 - 15:15 <td class=tdstyle>Ole Nielsen <td class=tdstyle>Keynote
    <tr>
    <td class=tdstyle>15:15 - 15:45 <td class=tdstyle colspan=2><b>Tea break</b>
    
    <tr>
    <td class=tdstyle>15:45 - 16:00 <td class=tdstyle style="color : red;"><b>N.K. Sinha</b> <td class=tdstyle style="color : red;"> Special Session

    <tr>
    <td class=tdstyle>16:00 - 16:20 <td class=tdstyle>Kannan Moudgalya <td class=tdstyle>NME ICT talk-->
    <tr>
    <td class=tdstyle style="width:210px;">Srikant and Sachin <td class=tdstyle><a href="/static/files/slides/python-on-aakash.pdf">Akash and Python: Py in the Sky</a>
    <tr>
    <td class=tdstyle style="width:210px;">Saket Choudhary <td class=tdstyle><a target="_blank" href="http://saketkc.github.com/scipy-presentation/">Scilab on Cloud</a>
    <tr>
    <td class=tdstyle style="width:210px;">Ami Tavory  <td class=tdstyle><a href="/static/files/slides/Scientific data analysis in pipelines.odp">Scientific Data Analysis Pipelines: Push, Pull, React, Or Schedule</a>
    <tr>
    <td class=tdstyle style="width:210px;">Ambuja Salgaonkar et al. <td class=tdstyle><a href="/static/files/slides/Scrablelight.pptx">SCRABLELIGHT: AN EDUCATIONAL GAME, DEVELOPED IN PYTHON</a>
    <!--tr>
    <td class=tdstyle>Jaidev Deshpande <td class=tdstyle><a href="/static/files/slides/Scrablelight.pptx">Time-Frequency Analysis with Python</a-->
    <tr>
    <td class=tdstyle style="width:210px;">Prasanta Mohapatra et al. <td class=tdstyle><a href="/static/files/slides/OCAMSS.pdf">OCAMSS– An Open source Platform for Multidisciplinary Structural Sizing of Composite Aircraft Wing</a>
    <tr>
    <td class=tdstyle style="width:210px;">Priyank Tiwari <td class=tdstyle><a href="/static/files/slides/Free chemical process simulator toolkit using SciPy.pptx">Free chemical process simulator toolkit using SciPy</a>
    <tr>
    <td class=tdstyle style="width:210px;">Madhu Sharma <td class=tdstyle><a href="/static/files/slides/Python based implementation of a chaos
based cryptosystem using external key
.pdf">Python based implementation of a chaos based cryptosystem using external key</a>
    <tr>
    <td class=tdstyle style="width:210px;">Samarth Shah <td class=tdstyle><a href="/static/files/slides/Raspberry Pi and Scientific Computing.pdf">Raspberry Pi and Scientific Computing</a>
    <tr>
    <td class=tdstyle style="width:210px;">Kunal Puri <td class=tdstyle><a href="/static/files/slides/PyZoltanscipy2012.pdf">Wrapping Zoltan with Cython</a>
    <tr>
    <td class=tdstyle style="width:210px;">Rupak Rokade <td class=tdstyle><a href="/static/files/slides/SBHS Virtual labs using Python
.pdf">SBHS Virtual Labs using Python</a>
    <tr>
    <td class=tdstyle style="width:210px;">B. Kanoj et al. <td class=tdstyle><a href="/static/files/slides/photo voltaic system.pdf">Simulation of Stand-alone Photovoltaic System using Python</a>
    <tr>
    <!--tr>
    <td class=tdstyle style="width:210px;">Krishnakant Mane <td class=tdstyle><a href=#3.15>Python as the first language</a>
    <tr>
    <td class=tdstyle style="width:210px;">Krishnakant Mane <td class=tdstyle><a href=#3.16>GNUKhata a case study for Python developers</a>
    <tr>
    <td class=tdstyle style="width:210px;">Abdulmajid Ansari <td class=tdstyle><a href=#3.17>Enhancing Open Source Blender 3D for Structural Analysis Using Python Tool</a>
    <tr>
    <td class=tdstyle style="width:210px;">Abdulmajid Ansari	<td class=tdstyle><a href=#3.18>Free 3D Jewelry Modeling Software using Python Scripting Tool in Blender</a-->
    <tr>
    <td class=tdstyle style="width:210px;">Ashish Ku Sharma <td class=tdstyle><a href="/static/files/slides/ahp.pdf">Design of Analytic Hierarchy Process Algorithm and Its Application for Vertical Handover in Cellular Communication</a>
    <tr>
    <td class=tdstyle style="width:210px;">Ashish Sharma <td class=tdstyle><a href="/static/files/slides/python tool for mcq.ppt">Simple Python based tool for preparing Randomized multi-set  multiple choice question papers
    <tr>
    <td class=tdstyle style="width:210px;">Satish Annigeri et al.<td class=tdstyle><a href="/static/files/slides/wecs.pdf">Steady State Analysis of Autonomous Wind Energy Conversion System Employing Induction Machines for Irrigation Purpose </a>
    <tr>
    <td class=tdstyle style="width:210px;">Gajanan Dhanorkar et al.<td class=tdstyle><a href="/static/files/slides/Differential Equation.pdf">Solving differential equation with graphical data Visualization using Python </a>
    </tr>
</table>

<hr>

<script>
var main = document.getElementsByName('main');

for (var j=0;j<main.length;j++)
{
    var trs = main[j].getElementsByTagName('tr');
    for (var i=1;i<trs.length;i++)
    {
        if(i%2==0)
        {
            trs[i].style.backgroundColor = "#C6E2FF";
            trs[i].style.color = "#003F87"
        }
        else
        {
            trs[i].style.backgroundColor = "white";
            trs[i].style.color = "#003F87"
        }
    }
}
</script>

{% endblock content %}

project/templates/talk/download-videos.html
{% extends "base.html" %}

{% block title %}Talk Videos{% endblock %}

{% block content %}
<h1>Videos for Download</h1>
<h2>First day talks </h2>
<p>
  <a href="http://www.fossee.in/sitefiles/Videos/SciPy_in_2010/first-day-part-1.ogv">
    Part 1
  </a>
&nbsp;  
  <a href="http://www.fossee.in/sitefiles/Videos/SciPy_in_2010/first-day-part-2.ogv">
   Part 2
  </a>
&nbsp;
  <a href="http://www.fossee.in/sitefiles/Videos/SciPy_in_2010/first-day-part-3.ogv">
    Part 3
  </a>
  <!--  <a href="http://www.fossee.in/sitefiles/Videos/SciPy_in_2010/first-day-part-4.ogv">
  Part 4
  </a> -->
  <br />
  <a href="http://www.fossee.in/sitefiles/Videos/SciPy_in_2010/first-day-part-5.ogv">
     Part 5
  </a>
&nbsp;
  <a href="http://www.fossee.in/sitefiles/Videos/SciPy_in_2010/first-day-part-6.ogv">
      Part 6
  </a>
&nbsp;  
  <a href="http://www.fossee.in/sitefiles/Videos/SciPy_in_2010/first-day-part-7.ogv">
      Part 7
  </a>
&nbsp;  
  <a href="http://www.fossee.in/sitefiles/Videos/SciPy_in_2010/first-day-part-8.ogv">
      Part 8
  </a>
<br />
<br />
<h3> This is an incomplete list we shall add more videos in the coming days. </h3>
</p><br />
{% endblock content %}

project/templates/talk/edit-talk.html
{% extends "base.html" %}

{% block title %}Edit Talk{% endblock %}

{% block content %}
<h1>Edit Talk</h1>

{% include '_errors.html' %}
<form action="{% url scipycon_edit_talk params.scope id %}" method="post">
    <fieldset>
      <legend>Edit Talk</legend>
      <table class="scipycon-default">
        {{ form }}
      </table>

      <button class="button left" type="submit">Save Changes</button>
    </fieldset>
</form>
{% endblock content %}

project/templates/talk/list-talks.html
{% extends "base.html" %}

{% block title %}My Talks{% endblock %}

{% block content %}
<h1>My Talks</h1>
{% if talk_list %}
<h3>List of the talks I have submitted.</h3>

<table class="list-talks">
  <tr>
    <th>Title</th>
    <th>Contact</th>
    <th>Topic</th>
    <th>Duration</th>
    <th>Audience type</th>
  </tr>
  {% for talk in talk_list %}
    <tr>
      <td><u><a href="/{{ params.scope }}/edit-talk/{{ talk.id }}/">{{ talk.title }}</a></u></td>
      <td>{{ talk.contact }}</td>
      <td>{{ talk.topic }}</td>
      <td>{{ talk.duration }}</td>
      <td>{{ talk.get_audience_display }}</td>
    </tr>
  {% endfor %}
</table>
{% else %}
<h2>No talks</h2>
{% endif %}
{% endblock content %}

project/templates/talk/submit-talk.html
{% extends "base.html" %}

{% block title %}Submit Talk Proposal{% endblock %}

{% block content %}
  <h1>Submit Talk Proposal</h1>

  {% include '_errors.html' %}

  <form action="{% url scipycon_submit_talk params.scope %}" method="post">
    {% if not user.is_authenticated %}
      <fieldset>
        <legend>Are you a member of this site?</legend>
        <table class="scipycon-default required">
          {{ login_form }}
        </table>

        <input type="hidden" name="action" value="login" />

        <button class="button left" type="submit">Login</button>
      </fieldset>

    </form>
    <br />

    <form action="{% url scipycon_submit_talk %}"
        enctype="multipart/form-data" method="post">
      <fieldset>
        <legend>Speaker Registration</legend>
        <table class="scipycon-default required">
          {{ register_form }}
        </table>

        <input type="hidden" name="action" value="register" />
      </fieldset>
    {% endif %}
    <br />

    <fieldset>
      <legend>Talk Submission</legend>
      <table class="scipycon-default required">
        {{ talk_form }}
      </table>

      <button class="button left" type="submit">Submit Talk</button>
    </fieldset>
  </form>
  {% if message %}
    <script type="text/javascript">
        $.jGrowl("{{ message }}");
     </script>
  {% endif %}
{% endblock content %}